name: Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - src/**
  schedule:
    - cron: '35 22 * * 5'

env:
  # Path to the CMake build directory.
  build: '${{ github.workspace }}/build'
  config: 'Release'

permissions:
  contents: read

jobs:
  test:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.6.*'
          setup-python: 'false'

      - name: Build
        shell: pwsh
        run: |
          mkdir ${{ env.build }}
          cd ${{ env.build }}
          cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=${{ env.config }} -DSKY_TESTS=ON ../
          cmake --build . --verbose

      - name: Test
        id: runtests
        run: |
          cd ${{ env.build }}/test
          xvfb-run ctest . -C ${{ env.config }} \
          --output-on-failure \
          --verbose \
          --output-junit unit-tests.xml

      - name: Prepare Test Report
        if: ${{ always() && steps.runtests.outcome == 'failure'}}
        uses: ./ci/processtestresults
        with:
            qt-tests: ${{ env.build }}/test/TestResults
            junit-output: ${{ env.build }}/test/unit-tests.xml
            html-output: ${{ env.build }}/test/testsreport.html

      - name: Publish Test Report
        if: ${{ always() && steps.runtests.outcome == 'failure'}}
        uses: actions/upload-artifact@v3
        with:
            name: TestReport
            path: |
              ${{ env.build }}/test/unit-tests.xml
